### PR TITLE
feat: Impish release

### PR DESCRIPTION
**Pull request by mmstick**
Merge only when ready to release Impish.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Just got a notification about 21.10 being available on a machine where I'd forgotten I had this branch added, so I can confirm the notification will work once this is merged.

**Comment by akionsight** [comment]
Looking forward to the release 👀

**Comment by olegur** [comment]
> Looking forward to the release 👀
@akionsight 

Turned on notifications for this because im excited for the release... you tricked me 🤣

**Comment by Daasin** [comment]
> Converted to draft because scary

Was this because something had to be halted or am I just reading into the joke too much? 😅

**Comment by diptaparna** [comment]
Will there ever be a Pop!_OS 21.10? Eagerly waiting for Gnome 40.

**Comment by leviport** [comment]
> Will there ever be a Pop!_OS 21.10? Eagerly waiting for Gnome 40.

Yes, of course. If you want to try the beta, you can get it early: https://github.com/pop-os/beta/

Please note that these PRs are essentially where we do our work. While we love to talk about Pop!\_OS, the [Pop!\_OS chat room](https://chat.pop-os.org) is a much more convenient place for us to do so.

**Review by jackpot51 — DISMISSED** [review]

**Comment by Daasin** [comment]
_**Enquiry: Is it possibly time to mark this as "Ready For Review" now instead of draft, given that all changes approved, checks have passed, and that the release is due on the 14th? (Or now in UTC time)**_

**Comment by jacobgkau** [comment]
> _**Enquiry: Is it possibly time to mark this as "Ready For Review" now instead of draft, given that all changes approved, checks have passed, and that the release is due on the 14th? (Or now in UTC time)**_

QA has not approved, and the purpose of marking as draft was to help ensure this is not accidentally merged before tomorrow.

I've locked discussion on this thread. We're glad everyone is excited for the release, stay tuned tomorrow!

**Comment by jacobgkau** [comment]
The most recent commit 76cd2fc to enable direct 20.04 -> 21.10 upgrades is working. I see 21.10 available in Settings, I get the notification after removing `dismissed` and setting `install_date` to before 20.10 release, and the upgrade from 20.04 to 21.10 works. (The COSMIC pages of G-I-S also display on first login.)

**Comment by leviport** [comment]
Changelogs look good:
Screenshot from 2021-12-13 21-10-24

However Jacob and I are now investigating something odd with legacy BIOS installs. Since they don't have recovery partitions, trying to update the recovery partition doesn't work. It probably shouldn't try to update a nonexistent recovery partition.

**Comment by jacobgkau** [comment]
https://github.com/pop-os/upgrade/pull/229 - This PR fixes the issue with legacy installs that Levi mentioned, and (if it's approved) should be merged into this branch _before_ this branch is merged into master.

**Review by leviport — APPROVED** [review]

**Comment by mmstick** [comment]
We will release once ISOs are ready, it's built on Launchpad, and we're ready to push it to release.

**Pull request merged**
