### PR TITLE
GTK Widget Support (used by GNOME Settings)

### PR DESCRIPTION
**Pull request by mmstick**
Includes all fixes and features for the GTK integration with GNOME Settings.

Based upon #34. This branch will be rebased once that PR is merged.

### CODE REVIEW

**Comment by brs17** [comment]
Once https://github.com/pop-os/upgrade/pull/34 gets reviewed by @pop-os/engineering , this should be based off of master instead of upgrade.

**Comment by brs17** [comment]
When running the upgrade from gnome-control-center, at some point g-c-c closes unexpectedly. There were no g-c-c logs but there seems to be some error logs from upgrade:

[gcc-go-away.log](https://github.com/pop-os/upgrade/files/3739736/gcc-go-away.log)

**Comment by mmstick** [comment]
Desktop notifications are now in this PR

**Comment by leviport** [comment]
I'm currently seeing a notification once the 19.10 upgrade has downloaded. Clicking this notification immediately reboots the system, without displaying the confirmation/changelog dialog first.

**Comment by mmstick** [comment]
It's currently defined as `|| reboot()`, but I can change that.

**Comment by brs17** [comment]
@mmstick let's rename the `Unsupported repositories detected` popup title from `Unsupported repositories detected` to `3rd party repositories`.

**Comment by leviport** [comment]
If I click the "cancel" button on that confirmation/changelog dialog I get returned to this screen. It says the download is complete, but with the "Upgrade" button missing. It may have disappeared when the confirmation/changelog dialog appeared.

Screenshot from 2019-10-17 15-13-34

**Comment by mmstick** [comment]
I need to `show()` the button on cancellation. The button's automatically hidden on click.

**Comment by brs17** [comment]
The notification is missing an icon, every other notification I have seen has an icon.

notification

**Comment by mmstick** [comment]
Our icon theme must be missing `distributor-logo-upgrade-symbolic`.

**Comment by leviport** [comment]
I initiated an upgrade, closed the G-C-C window, and watched `journalctl -f` until the download completed. No notification was spawned upon completion. If I logged out and back in, I saw the first notification, which says that a new version is available, not the one about "click here to restart".

**Comment by mmstick** [comment]
This is expected, because the widget exists only as long as GCC exists. Latest commit to the `upgrade_disco` branch at least allows the widget to outlive its panel. Working on a solution to prevent GCC from being closed.

**Comment by leviport** [comment]
I was testing the disappearing "upgrade" button after the download completed, and I discovered that clicking into the "Date & Time" category of G-C-C, then back to "About", then clicking on "Download" does not spawn the confirmation/changelog dialog and instead reboots the system.

**Comment by leviport** [comment]
Per our discussion on Slack, the second notification (after the download completed) should read:
```
Pop!_OS 19.10 is ready to upgrade
Click here to upgrade
```
The second line currently says "Click here to restart" and should be tweaked.

**Comment by leviport** [comment]
Finalized text from our Slack discussion:

Step 1:

    Upgrade available
    Pop!_OS 19.10 is available to download.

Click takes user to the About panel to click the download button.

Step 2:

    Upgrade Ready
    Pop!_OS is ready to upgrade to 19.10

Click takes user to the About panel to click the upgrade button and confirm reboot and upgrade button

**Comment by leviport** [comment]
The "Cancel" button in the dialog only closes the dialog. Maybe that button should cancel the upgrade so the next reboot doesn't take it to the systemd upgrade? Especially since that dialog is currently the only place the changelog is displayed. If a user sees something they are nervous about or don't like in the changelog, it's too late to skip or delay the upgrade at that point.

**Comment by leviport** [comment]
In regards to notifications, I'm seeing a couple things we might want to think about:

1. After a 19.04 user runs `sudo apt upgrade` to get the latest versions of pop-upgrade, they will not see a notification about 19.10 until they either reboot or log out. Should we find a way to make that notification appear sooner?

2. After clicking "Download" and moving focus over to a firefox window, the third party repos dialog spawns a notification that just says "Gnome Control Center Is Ready". I'm not sure if we're able to make that less generic, but it might be good if we can. Downloading doesn't proceed until that dialog is handled, and the notification might not be the best indicator that further action is required before the download continues.

**Comment by mmstick** [comment]
I'm not sure about the  "is ready" notification, since that's a generic notification from GNOME Shell when a background application did something that needs. I'll look into how I can get GNOME Settings to grab the focus, though.

**Comment by brs17** [comment]
> I initiated an upgrade, closed the G-C-C window, and watched `journalctl -f` until the download completed. No notification was spawned upon completion. If I logged out and back in, I saw the first notification, which says that a new version is available, not the one about "click here to restart".

@mmstick This seems to be related to the fact that if closing gnome-control-center before the 3rd party repositories pop-up appears, the pop-up will never appear and the download will not continue/happen.

**Comment by brs17** [comment]
Pop!_Shop notifications appear while/after downloading the new packages for 19.10. If a user selects the notification and proceeds with updates, upon rebooting the system, the system comes back in a broken state. Potentially this is related to `pop-upgrade` updating itself (away from the `upgrade-gtk` branch). Thoughts @mmstick ?

**Comment by mmstick** [comment]
The appcenter is supposed to be killed before packages are fetched for the current release. Was the appcenter re-opened at any point?

**Comment by leviport** [comment]
> I was testing the disappearing "upgrade" button after the download completed, and I discovered that clicking into the "Date & Time" category of G-C-C, then back to "About", then clicking on "Download" does not spawn the confirmation/changelog dialog and instead reboots the system.

This behavior has changed some, but I think it still needs work. Here is what I'm seeing:

After the download is complete, I click on the Upgrade button, which spawns the confirmation/changelog dialog. If I click "Cancel" to get out of that dialog, the "Upgrade" button still does not come back to the About page in Gnome Control Center. Instead of switching categories to get it back, I now have to close and re-open Gnome Control Center to get it back. 

Once I re-open Gnome Control Center, I do see the Upgrade button, but when I click it, I do not see the confirmation/changelog dialog reappear. Instead, the system abruptly reboots and begins the upgrade. Since the button is green and only says "Upgrade", I think it is important for the dialog to reappear since that is where we tell the user that their system will reboot.

**Comment by brs17** [comment]
> The appcenter is supposed to be killed before packages are fetched for the current release. Was the appcenter re-opened at any point?

@mmstick, it appears that Pop!_Shop may not be getting closed after all. Just ran an upgrade without touching anything else and `ps` shows that the center is still running. Perhaps additional logs from `pop-upgrade` about killing Pop!_Shop would be helpful to debug?

**Comment by mmstick** [comment]
There should be a log in `pop-upgrade` that states: `killing io.elementary.appcenter`.

**Comment by brs17** [comment]
When selecting `Cancel` after the upgrade has downloaded on the pop-up with the changelog, the following is what the `About` panel looks like afterwards.
Screenshot from 2019-10-18 11-03-32

**Comment by mmstick** [comment]
I remember that 19.04 had issues with killing the appcenter by name. That may be related.

**Comment by mmstick** [comment]
The path for the appcenter is apparently `io.elementary.appcenter (deleted)`.

**Comment by brs17** [comment]
On the `About` panel, the OS Upgrade panel should be an expander similar to firmware-manager, where it expands showing the changelog.

**Comment by brs17** [comment]
When selecting cancel on the "Reboot and Upgrade" pop-up - this is what the page looks like
Screenshot from 2019-10-18 14-30-39

Rebooting then does start the upgrade process (it shouldn't).

**Comment by mmstick** [comment]
What's the commit of that version of pop-upgrade?

**Comment by leviport** [comment]
@mmstick That was this one: https://github.com/pop-os/upgrade/pull/37/commits/c698953ce46b87979e71689cf0ecdb66de334f73

**Pull request merged**
