### PR TITLE
fix: Move user extensions to extensions.bak on upgrade

### LINKED ISSUE #166: Upgrades > Disable current extensions
Dash to Dock is likely to cause problems. Should we disable all extensions for this upgrade?

Are there other upgrade considerations?

### PR DESCRIPTION
**Pull request by mmstick**
Closes #166

### CODE REVIEW

**Review by jackpot51 — COMMENTED** [review]
My only concern - maybe we want to signal that extensions were disabled to the user? Could be in GIS. @maria-komarova @WatchMkr any thoughts?

**Comment by maria-komarova** [comment]
That's a good idea. I believe we should. Just need a copy that includes a reason for why we are disabling them. What do you think would be the best way to describe it?

**Comment by jackpot51** [comment]
I think if extensions are detected in the backup folder, we can say (substitute user for the username, and make the paths links to the folders):

"
Your custom GNOME Shell extensions have been moved from:
/home/user/.local/share/gnome-shell/extensions
To this backup folder:
/home/user/.local/share/gnome-shell/extensions.bak
You can move them back if you wish to re-enable them.
"

We can also add something about how we do this because unofficial extensions can cause issues, are not tested, and should be enabled one at a time to be clear about where bugs are coming from.

**Comment by jacobgkau** [comment]
Would it be better to recommend the extensions be reinstalled from extensions.gnome.org if possible instead of by moving the files back, since that would make sure the most up-to-date versions are being installed? Just a thought.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
The conflict with `ubuntu-release-upgrader-core` is causing a problem in its current implementation:

```
system76@pop-os:~$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libpop-upgrade-gtk pop-upgrade
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
system76@pop-os:~$ apt policy pop-upgrade
pop-upgrade:
  Installed: 0.1.1~1622662637~20.10~b797d3d
  Candidate: 0.1.1~1624648624~20.10~b77e3ff
  Version table:
     0.1.1~1624648624~20.10~b77e3ff 1002
       1002 http://apt.pop-os.org/staging/dev groovy/main amd64 Packages
 *** 0.1.1~1622662637~20.10~b797d3d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
system76@pop-os:~$ sudo apt install pop-upgrade=0.1.1~1624648624~20.10~b77e3ff
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-distro-info python3-distupgrade python3-update-manager
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpop-upgrade-gtk
The following packages will be REMOVED:
  ubuntu-release-upgrader-core update-manager-core
The following packages will be upgraded:
  libpop-upgrade-gtk pop-upgrade
2 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
Need to get 2,862 kB of archives.
After this operation, 750 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
system76@pop-os:~$
```

It looks like I could make it install without removing anything critical, but an `upgrade` or even a `dist-upgrade` doesn't work.

**Comment by jacobgkau** [comment]
A transitional/empty package for whichever Ubuntu package(s) we're trying to remove might work better than just provides/conflicts/replaces, or maybe there's a better solution. I just put #177 in today, it doesn't need to be fixed before 21.04 release-- do-release-upgrade has been upgrading people to 21.04 since Ubuntu released 21.04, so I think the majority of that impact has already passed. Although fixing it now rather than later would be nice if there's an easy fix for this packaging issue, since we know for certain that some users do attempt to use do-release-upgrade.

**Comment by jackpot51** [comment]
Why is it being depended on in the first place?

**Comment by jacobgkau** [comment]
@jackpot51 We're wanting `do-release-upgrade` to not exist on Pop!_OS. Users in cases like [this](https://github.com/pop-os/pop/issues/1727) try to use `do-release-upgrade` and don't know how to handle subsequent issues. The only options on Pop!_OS should be `pop-upgrade release upgrade` or, if a user really knows what they're doing, updating their sources lists manually Debian-style.

I wouldn't necessarily expect the packaging change here to affect the TTY prompt, but I can test that once it builds. Even if the prompt still shows up in TTYs, we don't want users running the script anyway, and getting "command not found" will already be an improvement over a broken upgrade.

**Comment by jackpot51** [comment]
Yep, I get that. These are the files in that package, so I think the motd crap should be gone as well:

```
ubuntu-release-upgrader-core: /etc/update-manager/meta-release
ubuntu-release-upgrader-core: /etc/update-manager/release-upgrades
ubuntu-release-upgrader-core: /etc/update-motd.d/91-release-upgrade
ubuntu-release-upgrader-core: /usr/bin/do-release-upgrade
ubuntu-release-upgrader-core: /usr/lib/ubuntu-release-upgrader/check-new-release
ubuntu-release-upgrader-core: /usr/lib/ubuntu-release-upgrader/do-partial-upgrade
ubuntu-release-upgrader-core: /usr/lib/ubuntu-release-upgrader/release-upgrade-motd
ubuntu-release-upgrader-core: /usr/share/apport/package-hooks/source_ubuntu-release-upgrader.py
ubuntu-release-upgrader-core: /usr/share/doc/ubuntu-release-upgrader-core/AUTHORS
ubuntu-release-upgrader-core: /usr/share/doc/ubuntu-release-upgrader-core/README
ubuntu-release-upgrader-core: /usr/share/doc/ubuntu-release-upgrader-core/changelog.gz
ubuntu-release-upgrader-core: /usr/share/doc/ubuntu-release-upgrader-core/copyright
ubuntu-release-upgrader-core: /usr/share/man/man8/do-release-upgrade.8.gz
ubuntu-release-upgrader-core: /usr/share/polkit-1/actions/com.ubuntu.release-upgrader.policy
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/DistUpgrade.cfg
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/additional_pkgs.cfg
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/deb2snap.json
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/demoted.cfg
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/mirrors.cfg
ubuntu-release-upgrader-core: /usr/share/ubuntu-release-upgrader/removal_blacklist.cfg
```

**Comment by jacobgkau** [comment]
The transitional package has not fixed the issue, 0e1038c still has the same problem upgrading/installing as before. If we're doing the empty package to override Ubuntu's, then do we not need all of the provides/conflicts/replaces lines?

**Comment by jacobgkau** [comment]
a826462 installs on Groovy with a normal `apt upgrade`. However, `ubuntu-release-upgrader-core` is not being updated to our version (so `do-release-upgrade` is still present.)

```
system76@pop-os:~$ apt policy ubuntu-release-upgrader-core
ubuntu-release-upgrader-core:
  Installed: 1:20.10.16
  Candidate: 0.1.1~1624660103~20.10~a826462
  Version table:
 *** 1:20.10.16 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main i386 Packages
        100 /var/lib/dpkg/status
     1:20.10.12 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     0.1.1~1624660103~20.10~a826462 1002
       1002 http://apt.pop-os.org/staging/dev groovy/main amd64 Packages
system76@pop-os:~$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
system76@pop-os:~$ sudo apt install ubuntu-release-upgrader-core=0.1.1~1624660103~20.10~a826462
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-distro-info python3-distupgrade python3-update-manager
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  update-manager-core
The following packages will be DOWNGRADED:
  ubuntu-release-upgrader-core
0 upgraded, 0 newly installed, 1 downgraded, 1 to remove and 0 not upgraded.
Need to get 1,160 B of archives.
After this operation, 538 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

`update-manager-core` is installed because `ubuntu-standard` recommends it; it might also need an empty package to replace it so it doesn't get removed during this operation.

**Comment by jacobgkau** [comment]
I did complete the upgrade on a826462, and the extensions were not disabled/moved.

**Comment by mmstick** [comment]
I take it that there were no `disabling gnome-shell extensions for` messages in the daemon logs?

**Comment by jacobgkau** [comment]
> I take it that there were no `disabling gnome-shell extensions for` messages in the daemon logs?

Correct, that line did not appear in the logs, same as before.

**Comment by jacobgkau** [comment]
956e7a9 is still not disabling extensions. I got this log output after the packages got done downloading:

```
Jun 28 07:42:04 pop-os pop-upgrade[5908]: Conf xbrlapi (6.3+dfsg-1ubuntu1 Ubuntu:21.04/hirsute [amd64])
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:5: attempting to disable gnome-shell extensions
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("root") with UID 0
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("daemon") with UID 1
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("bin") with UID 2
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("sys") with UID 3
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("sync") with UID 4
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("games") with UID 5
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("man") with UID 6
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("lp") with UID 7
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("mail") with UID 8
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("news") with UID 9
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("uucp") with UID 10
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("proxy") with UID 13
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("www-data") with UID 33
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("backup") with UID 34
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("list") with UID 38
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("irc") with UID 39
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("gnats") with UID 41
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("nobody") with UID 65534
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("systemd-timesync") with UID 100
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("systemd-network") with UID 101
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("systemd-resolve") with UID 102
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("messagebus") with UID 103
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("syslog") with UID 104
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("_apt") with UID 105
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("geoclue") with UID 106
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("colord") with UID 107
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("gnome-initial-setup") with UID 108
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("speech-dispatcher") with UID 109
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("gdm") with UID 110
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("avahi-autoipd") with UID 111
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("avahi") with UID 112
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("tss") with UID 113
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("pulse") with UID 114
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("rtkit") with UID 115
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("usbmux") with UID 116
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("_flatpak") with UID 117
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("cups-pk-helper") with UID 118
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("saned") with UID 119
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("dnsmasq") with UID 120
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("tcpdump") with UID 121
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("uuidd") with UID 122
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("systemd-coredump") with UID 999
Jun 28 07:42:04 pop-os pop-upgrade[3459]: [INFO ] pop_upgrade src/gnome_extensions.rs:10: found user Some("system76") with UID 1000
Jun 28 07:42:04 pop-os pop-upgrade[5916]: pop-upgrade was already not hold.
```

**Comment by mmstick** [comment]
I see the problem. This last commit should fix it.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
After completing an upgrade from 20.10 on fec6575, extensions were disabled. However, the `pop-comsic` package with the COSMIC extension was not installed, and the dock and multi-monitors extensions were also not installed. Additionally, the apps pinned to favorites were different than our defaults:

Screenshot from 2021-06-28 10-00-30

Further investigation showed that `pop-session` had not been upgraded:

session

The `pop-upgrade` log doesn't have any mention of `pop-session`: [upgrade.txt](https://github.com/pop-os/upgrade/files/6727735/upgrade.txt)

This is the first time I've seen anything like this happen. The 20.10 installation that I upgraded from was a fresh image with Caffeine and Dash to Dock installed, and all updates applied, but no other changes. I'm going to see if it happens a second time, but wanted to post now since this would obviously be a significant problem.

**Comment by jacobgkau** [comment]
Ok, the reason `pop-session` did not get upgraded is because it depends on `gnome-shell-extension-cosmic-dock`, which is not available:
```
system76@pop-os:~$ sudo apt install pop-session=5.0.0~1624644618~21.04~c22ce18
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-session : Depends: gnome-shell-extension-cosmic-dock but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by jacobgkau** [comment]
The `gnome-shell-extension-cosmic-dock` package needs to be released from the proposed PPA into the stable PPA. @jackpot51 / @mmstick

**Comment by jackpot51** [comment]
@jacobgkau doing it now!

**Comment by jacobgkau** [comment]
This is working as intended now.

This takes effect for older Pop versions where we're not going to be displaying a notice in GNOME Initial Setup, such as 18.04 -> 20.04. I'm inclined to think this should be okay since most upgrades should be to the latest version, but I wanted to mention it.

Also, the `do-release-upgrade` conflict is not working-- the script is still installed. It looks like this is due to `update-manager-core` being removed, no change from Friday. We should either try to get that working or remove that from the PR so it doesn't cause held-back packages.

```
system76@pop-os:~$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
system76@pop-os:~$ apt policy ubuntu-release-upgrader-core 
ubuntu-release-upgrader-core:
  Installed: 1:21.04.13
  Candidate: 0.1.1~1624890905~21.04~fec6575
  Version table:
 *** 1:21.04.13 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main i386 Packages
        100 /var/lib/dpkg/status
     1:21.04.10 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main i386 Packages
     0.1.1~1624890905~21.04~fec6575 1002
       1002 http://apt.pop-os.org/staging/dev hirsute/main amd64 Packages
system76@pop-os:~$ sudo apt install ubuntu-release-upgrader-core=0.1.1~1624890905~21.04~fec6575
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-distro-info python3-distupgrade python3-update-manager
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  update-manager-core
The following packages will be DOWNGRADED:
  ubuntu-release-upgrader-core
0 upgraded, 0 newly installed, 1 downgraded, 1 to remove and 0 not upgraded.
Need to get 1,160 B of archives.
After this operation, 538 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.

```

**Comment by jacobgkau** [comment]
We're getting closer. An `apt full-upgrade` now offers to switch to our version of `update-manager-core` and `ubuntu-release-upgrader-core` where it previously did not, although a regular `apt upgrade` still doesn't do it.

```
system76@pop-os:~$ apt policy update-manager-core
update-manager-core:
  Installed: 1:21.04.10
  Candidate: 0.1.1~1624906392~21.04~4749628
  Version table:
 *** 1:21.04.10 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main i386 Packages
        100 /var/lib/dpkg/status
     1:21.04.8 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main i386 Packages
     0.1.1~1624906392~21.04~4749628 1002
       1002 http://apt.pop-os.org/staging/dev hirsute/main amd64 Packages
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
system76@pop-os:~$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  python3-distro-info ubuntu-release-upgrader-core
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  python3-distupgrade python3-update-manager
The following packages will be DOWNGRADED:
  ubuntu-release-upgrader-core update-manager-core
0 upgraded, 0 newly installed, 2 downgraded, 2 to remove and 0 not upgraded.
Need to get 2,312 B of archives.
After this operation, 1,427 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

It looks like the issue now is that it's wanting to remove `python3-distupgrade` and `python3-update-manager`. `update-manager-core` requires `python3-update-manager` and `ubuntu-release-upgrader-core` requires `python3-distupgrade`, but I'm not sure why it's trying to remove the two Python packages instead of just leaving them to be autoremoved later. After proceeding with the full-upgrade, I'm able to install them again without issue.

**Comment by jackpot51** [comment]
@mmstick At this point I feel we should drop the attempt to replace ubuntu-release-upgrader-core.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Confirmed the extension disabling is still working after the latest changes.

**Pull request merged**
