### PR TITLE
feat(gtk): Show loading animation while checking for updates

### LINKED ISSUE #132: (gtk) Loading indicator for OS Upgrade page in Settings
As mentioned in [this review](https://github.com/pop-os/upgrade/pull/127#pullrequestreview-532640871), the OS Upgrade page is blank while `pop-upgrade` checks for and performs a self-update.

When a self-update isn't required:

upgrade-i-screencast1

When a self-update is required:

upgrade-i-screencast2

It would be nice if there was either a loading spinner, text like "Checking for updates...", or some other indication to let users know that the system is working and not just loading slowly in those few seconds.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #132

### CODE REVIEW

**Review by ids1024 — DISMISSED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
The loading spinner looks good. However, it's just spinning indefinitely:

loading

(All `pop-upgrade` packages are up-to-date and the page is not proceeding past the spinner.)

**Comment by mmstick** [comment]
That should be fixed with this change

**Review by ids1024 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
@mmstick It looks like it's still happening.

Screenshot from 2020-11-19 13-41-33

**Review by jacobgkau — APPROVED** [review]
Looks good now, both when checking for a self-update and when actually performing a self-update.

- If a self-update is not available, I briefly see the spinner with no text, followed by the actual page.
- If a self-update is available, I see the spinner with no text, followed by "Updating the upgrade service", and finally "Checking for updates" before the actual page is displayed.

Release upgrades still work.

**Pull request merged**
