### PR TITLE
Prevent release notifications on LTS if the install time exceeds the next release time

### LINKED ISSUE #74: Dismiss upgrade notification on LTS install post non-LTS release
When an LTS release is installed after the release of a non-LTS version, the user should not be notified of a new Pop!_OS release until the next version comes out. (e.g. Install 18.04 in December of 2019 and should not be notified of a new release until 20.04).

### PR DESCRIPTION
**Pull request by mmstick**
Closes #74

### CODE REVIEW

**Comment by mmstick** [comment]
It should still work after a system restart, since the change only applies to the CLI client which is responsible for creating the notifications.

**Comment by brs17** [comment]
> It should still work after a system restart, since the change only applies to the CLI client which is responsible for creating the notifications.

I have rebooted a number of times with no success.

**Comment by mmstick** [comment]
I will notify you when I get it working here.

**Comment by mmstick** [comment]
Found issue. Error in logs: `19.10 is not a valid codename`.

**Comment by mmstick** [comment]
@brs17 Seems to be working now

**Comment by mmstick** [comment]
So it needs to be a once-only operation

**Comment by mmstick** [comment]
@brs17 This is working now

**Pull request merged**
