### PR TITLE
Post-Release Improvements

### PR DESCRIPTION
**Pull request by mmstick**
- Display a better error message for core package errors caused by `gnome-software` being installed
- Remove the `gnome-software` package and add `sessioninstaller` as a core package to prevent the core package error from happening due to `gnome-software` being installed.
- Try to repair dpkg and apt errors before performing a release upgrade.
- Display "Plug into power" in changelog dialog when on battery.
- Move the progress bar beneath the status text and button.
- Improve the progress bar to represent current progress better.

### CODE REVIEW

**Comment by brs17** [comment]
Wouldn't we rather just work to make `sessioninstaller` a recommends instead of a depends and keep this from breaking in general? @jackpot51 and I (and I think @mmstick ) spoke about it this morning.

**Comment by WatchMkr** [comment]
sessioninstaller functionality should be in Pop Shop. I think elementary would like this as well. Not sure how that fits in here however - seems a short term fix is appropriate.

**Comment by mmstick** [comment]
I just noticed that we have an issue with the progress bar giving a misleading progress %. Currently investigating the cause.

**Comment by brs17** [comment]
Looks like upgrade fails when looking to remove a package that doesn't exist (eg. `ureadahead`)

```
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:284: event processed
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:468: package upgrade: processing triggers for libc-bin
Oct 22 16:52:33 pop-os gnome-control-center.desktop[1491]: Initiated(Download("19.10"))
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:682: upgrading release from 19.04 to 19.10, with 1
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:242: attempting release upgrade, using a offline upgrade
Oct 22 16:52:33 pop-os pop-upgrade[887]: killing io.elementary.appcenter
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/repair/mod.rs:27: performing release repair
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/repair/sources.rs:37: ensuring that the proprietary pop repo is added
Oct 22 16:52:33 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/repair/sources.rs:69: PPA system76/pop found: not adding
Oct 22 16:52:34 pop-os pop-upgrade[887]: Reading package lists...
Oct 22 16:52:34 pop-os pop-upgrade[887]: Building dependency tree...
Oct 22 16:52:34 pop-os pop-upgrade[887]: Reading state information...
Oct 22 16:52:34 pop-os pop-upgrade[887]: The following packages were automatically installed and are no longer required:
Oct 22 16:52:34 pop-os pop-upgrade[887]:   app-install-data gir1.2-gstreamer-1.0
Oct 22 16:52:34 pop-os pop-upgrade[887]: Use 'apt autoremove' to remove them.
Oct 22 16:52:35 pop-os pop-upgrade[887]: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Oct 22 16:52:35 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:468: release upgrade: removing deprecated and/or conflicting packages
Oct 22 16:52:35 pop-os gnome-control-center.desktop[1491]: UpgradeEvent(RemovingConflicts)
Oct 22 16:52:35 pop-os pop-upgrade[887]: Reading package lists...
Oct 22 16:52:35 pop-os pop-upgrade[887]: Building dependency tree...
Oct 22 16:52:35 pop-os pop-upgrade[887]: Reading state information...
Oct 22 16:52:35 pop-os pop-upgrade[887]: E: Unable to locate package ureadahead
Oct 22 16:52:35 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:284: event processed
Oct 22 16:52:36 pop-os pop-upgrade[887]: [INFO ] pop_upgrade src/daemon/mod.rs:468: release upgrade result: Err(ConflictRemoval(Custom { kind: Other, error: StringError("command failed with 
Oct 22 16:52:36 pop-os gnome-control-center.desktop[1491]: Error(Upgrade(Status(StatusError("conflicting and/or deprecated packages could not be removed"))))
Oct 22 16:52:36 pop-os gnome-control-center.desktop[1491]: Setting status to 0
```

gtk window had an error: `failed to upgrade OS: failed status: conflicting and/or deprecated packages could not be removed`

**Comment by mmstick** [comment]
^ Needs to check if a conflicting package is installed before trying to remove it. Passing the package list to `dpkg-query --show --showformat='${db:Status-Status}\n'`, and then filtering status by line, will do this.

**Pull request merged**
