### PR TITLE
check test coverage

### PR DESCRIPTION
**Pull request by danieleades**
note that this is stacked on #156 and should be rebased once that's merged

rationale - https://github.com/pop-os/system76-power/issues/237#issue-859701869

### CODE REVIEW

**Comment by mmstick** [comment]
@danieleades I'm going to merge all your branches together into a single branch. Multiple branches to test is a nightmare for QA. Will try to get the merged in the active development branch.

**Comment by danieleades** [comment]
> @danieleades I'm going to merge all your branches together into a single branch. Multiple branches to test is a nightmare for QA. Will try to get the merged in the active development branch.

Whatever is easiest for you.

Do QA still need to do manual testing if there's 0 code changes?

**Comment by danieleades** [comment]
> @danieleades I'm going to merge all your branches together into a single branch. Multiple branches to test is a nightmare for QA. Will try to get the merged in the active development branch.

Whatever is easiest for you.

Do QA still need to do manual testing if there's 0 code changes?

**Comment by mmstick** [comment]
All PRs must pass regression tests in the lab before they're merged. So it's better not to batch your changes together in a single PR (preferrably on the current development branch)

**Comment by mmstick** [comment]
Closing all these PRs now. I'll have them redone in the dev branch

**Pull request closed without merging**
