### PR TITLE
feat: Replace do-release-upgrade

### LINKED ISSUE #177: Conflict with do-release-upgrade
Users sometimes run into problems after running Ubuntu's `do-release-upgrade` script, which we do not test or support. `do-release-upgrade` is provided by `ubuntu-release-upgrader-core`, which is a dependency of `update-manager-core`, which is a recommends of `ubuntu-standard`.

`pop-upgrade` should ensure that `do-release-upgrade` is not present on the system, perhaps by conflicting with `update-manager-core` or conflicting with/providing `ubuntu-release-upgrader-core`.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #177

### CODE REVIEW

**Comment by ids1024** [comment]
This would prevent `pop-upgrade` from updating without an `apt full-upgrade`, right?

Another solution would be to package our own version of `ubuntu-release-upgrader-core` with a script saying to use `pop-upgrade` instead.

**Comment by mmstick** [comment]
Similar to nvidia-graphics-driver updates, yes.

**Comment by bflanagin** [comment]
It looks like the fix would require users to run `dist-upgrade` on their systems. Is there a way to avoid this so a novice user isn't greeted with an error message when installing via pop-shop?

**Comment by jacobgkau** [comment]
Re: `nvidia-graphics-driver` updates, our NVIDIA driver updates don't require `dist-upgrade`/`full-upgrade`, we specifically test to make sure they install with a regular `upgrade`.

**Comment by mmstick** [comment]
Depends on the update. Any update that deprecates and transitions to a newer set of packages requires full-upgrade.

**Comment by jacobgkau** [comment]
> Software centers perform a full-upgrade by default.

Are you sure? When we [renamed the COSMIC Dock extension](https://github.com/pop-os/cosmic-dock/pull/20) during the beta, users got error messages through the Pop!_Shop and had to run `sudo apt full-upgrade` manually in a terminal, we know that because they kept asking about it in the Mattermost chat.

**Pull request merged**
