### PR TITLE
Upgrade Improvements

### PR DESCRIPTION
**Pull request by mmstick**
- Show progress for prerequisites being installed during the offline upgrade, to prevent people from assuming that nothing is happening when this process takes a lot of time to complete.
- Be explicit about declaring the candidate version of prerequisites to install when doing that prerequisite upgrade, to ensure that apt knows that we really do want the latest candidate installed.
- Cleans up the way prerequisites are installed, with all packages determined required to be appended to an array for a single install invocation, and adds ppp and libm0 to the list of packages that need the extra handholding at this stage.
- Adds similar repair fix for the `pop-upgrade repair` routine, which ensures that candidate versions of each of these packages are installed when conflicts occur.
- Improvements to old-releases handling when repairing, upgrading, and restoring.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Tested an 18.04 -> 20.04 upgrade in a VM using the problem package list from [this comment](https://github.com/pop-os/upgrade/pull/142#issuecomment-832205986), then 20.04 -> 21.10 on the same installation. https://github.com/pop-os/upgrade/issues/164 is still occurring, but that's not a regression.

Even after I worked around #164, the 20.04 -> 21.10 upgrade failed. The system did not power off/reboot properly after the offline upgrade, and upon booting again, I had Focal packages with Impish sources. I will attempt to replicate this from a fresh 20.04 installation using a modified version of the package list.

**Comment by jacobgkau** [comment]
I recreated the failure from a fresh 20.04 LTS installation (with all updates applied) using this package list: [installed-focal-oneline.txt](https://github.com/pop-os/upgrade/files/7823847/installed-focal-oneline.txt)

Here is what I see after `Upgrade complete. Now rebooting`:

image

(It seems this output is normal in a VirtualBox installation, but the system does not finish powering off/rebooting.)

Upon rebooting, GDM is not using the Pop theme, and I have mixed package versions (e.g. `pop-default-settings` is on a 20.04 version, but `gdm3` is on a 21.10 version.)

Currently performing the upgrade one more time on stable pop-upgrade to confirm this is a regression.

**Comment by jacobgkau** [comment]
Hmm... I thought this worked the very first time I tried on stable, but I seem to have encountered the same issue testing on stable now. I'll try running the upgrade script manually to see where it might be having an issue.

**Comment by jacobgkau** [comment]
Here are logs from running `pop-upgrade release upgrade` and then `sudo /usr/lib/pop-upgrade/upgrade.sh` on this branch. The only change I made to `upgrade.sh` before running was removing the line to reboot.

[upgrade-1.txt](https://github.com/pop-os/upgrade/files/7824071/upgrade-1.txt)
[upgrade-2.txt](https://github.com/pop-os/upgrade/files/7824072/upgrade-2.txt)

**Comment by jacobgkau** [comment]
6197b64 seems to fail faster. upgrade.sh output: [upgrade.txt](https://github.com/pop-os/upgrade/files/7849058/upgrade.txt)

**Comment by mmstick** [comment]
With the last commit, pop-upgrade is no longer burdened by the cursed package list.

**Comment by jacobgkau** [comment]
Confirmed the list from https://github.com/pop-os/upgrade/pull/142#issuecomment-832205986 is no longer killing the 20.04 -> 21.10 upgrade!

I noticed that if `chromium-browser` and `chromium-codecs-ffmpeg-extra` were installed on 20.04, after the upgrade to 21.10 is complete, `chromium-browser` immediately has an update available to Ubuntu's version (and installing that update pulls in the snap, while our outdated `chromium` package is also still installed.) Confirmed this isn't a regression.

**Comment by jacobgkau** [comment]
While 66b2eb3 fixed the upgrade from 20.04 -> 21.10, it seems to have broken the upgrade from 18.04 -> 20.04, with the package list.

**Comment by mmstick** [comment]
I'll see what I can do about that

**Comment by jacobgkau** [comment]
I'm running the script manually now, I saw `Command line option 'y' [from '-y'] is not understood` near the beginning, in case that's related.

**Comment by jacobgkau** [comment]
Here was the log from 66b2eb3: [upgrade-output-1804.txt](https://github.com/pop-os/upgrade/files/7857182/upgrade-output-1804.txt)

**Comment by jacobgkau** [comment]
Still failing on 412ac24, here is the output: [upgrade-1804-output.txt](https://github.com/pop-os/upgrade/files/7858297/upgrade-1804-output.txt)

**Comment by jacobgkau** [comment]
https://github.com/pop-os/upgrade/issues/164 is still happening as mentioned earlier (still not a regression), but 6dbf517 works for 18.04 -> 20.04 and 20.04 -> 21.10 in a virtual machine.

**Comment by jacobgkau** [comment]
Just to be clear, I'm not sure if I can actually test whether the attempted fixes for https://github.com/pop-os/upgrade/issues/164 are working, since I'm on stable pop-upgrade after the 18.04 -> 20.04 upgrade and it's the old version that tries to install the new version from there. Unless we know of a way to artificially induce the `grub-pc package is being upgraded` screen, in which case I could test the self-upgrade from the branch to stable after removing the staging repo.

Still doing regression testing aside from that.

**Comment by jacobgkau** [comment]
I guess the question might be why this prompt is showing up even though the `grub-pc` update should have happened during the offline portion of the upgrade.

**Comment by mmstick** [comment]
debconf dialogs can show up even if you define `noninteractive` because `dpkg` doesn't listen to that setting. It does require setting `--force-confdef` to have it assume the default configuration in the file, and `--force-confold` to prefer existing configs if they already exist.

Unsure on the best way to induce the dialog. It's commonly seen each time it updates when there's no pre-existing grub config.

**Comment by jacobgkau** [comment]
This doesn't seem to fix https://github.com/pop-os/upgrade/issues/243, is it supposed to? (The description mentions old-releases improvements.)

On a 20.10 virtual machine, I added the Focal staging branch (since this branch is not being built for Groovy), then tried to run pop-upgrade. Here's the output: [groovy.txt](https://github.com/pop-os/upgrade/files/7865144/groovy.txt)

Not sure if https://github.com/pop-os/upgrade/issues/116 is related to this since it looks like the configured staging branch was reverted from focal to groovy at some point in the process, but I'm also seeing strange behavior with the old-releases URLs sometimes working and sometimes not when just running `apt update` (possibly seems like it doesn't work for a minute after updating the repo config?): [groovy-apt-update.txt](https://github.com/pop-os/upgrade/files/7865145/groovy-apt-update.txt)

I'm inclined to move forward with this PR as-is to get the other fixes in, just keeping track of what is and isn't addressed.

**Comment by mmstick** [comment]
Sure, we can have it move forward as-is. There's an attempt to fix old-releases. Will follow up with a PR in the future for that.

**Review by jacobgkau — APPROVED** [review]
I've tested d989c8b in the following configs, all successful:
- 18.04 -> 20.04 -> 21.10 with the extensive cursed package list in a VM
- 20.04 -> 21.10 with wine, kdenlive, steam, and lutris on a physical machine
- 21.04 -> 21.10 with wine, kdenlive, steam, lutris, ardour, and vlc on a physical machine

Contains some good fixes and no regressions from what's currently published.

**Pull request merged**
