### PR TITLE
i18n(bn) spelling

### PR DESCRIPTION
**Pull request by Oymate**

### CODE REVIEW

**Comment by Oymate** [comment]
It's just a translation character update, does this need codecov?

**Review by leviport — APPROVED** [review]
I'm not fluent, but this looks like a good correction to me. Thanks!

**Comment by Oymate** [comment]
Yup I forgot to clear the foreign character

**Comment by Oymate** [comment]
@leviport do you by chance disable website fonts? [I would have liked to see what font the Bengali text is in that picture :) ]

**Comment by leviport** [comment]
>@leviport do you by chance disable website fonts? [I would have liked to see what font the Bengali text is in that picture :) ]

I don't do anything fancy to my browser besides install Darkreader, so the fonts in my screenshot are probably whatever comes up by default in Firefox on Pop!\_OS 21.04

**Comment by Oymate** [comment]
@leviport do you by chance disable website fonts? [I would have liked to see what font the Bengali text is in that picture :) ]

**Comment by Oymate** [comment]
@leviport right-click>view source > on the right side of the html code, see the fonts

**Comment by leviport** [comment]
@Oymate does this tell you what you need?

**Pull request merged**
